txtdirect/txtdirect

.travis.yml
Makefile

Moves build logic for Travis CI to Makefile
fixes #30
```release-note
Move CI build logic to Makefile
```

Move CI build logic entirely in Makefile

---

txtdirect.go

Checks if the host variable contains a port and removes it before use in zone since adding a port to the zone will cause it to break.
fixes #39

Remove port if host includes one

---

txtdirect.go

Changes the DNS TXT lookup to add a trailing dot to the end of the zone in order to speed up lookup requests by avoiding the use of the entire DNS search path.
fixes #43

Change DNS TXT lookup to use the absolute zone

---

Makefile

Disables caddy telemetry at compile time from TXTDirect so that data collection follows an opt-in approach.
fixes #48

Disable caddy telemetry

---

gometa.go
path.go

Adds checks for paths that contain "internal" folders and returns an error since importing of internal packages should be prevented.
fixes #27

Prevent internal folder path

---

gometa_test.go

Adds a test that ensures an error is returned when "/internal" is included in the path.

Add test for 'internal' folder in path

---

Makefile

Disables caddy telemetry in Travis build. Also removes the unnecessary 'g' in the regex.
fixes #48

Disable caddy telemetry in Travis build

---

txtdirect.go

Since we only check the first _redirect TXT record, if multiple _redirect records are provided, TXTDirect will only choose the first record. To address this issue, it is necessary to check the slice of TXT records and if it does not equal 1, we now return an error. 
Also, the maximum length of a _redirect record cannot exceed 255 characters. This PR addresses that issue as well by returning an error when a _redirect record exceeds 255 characters.
fixes #40

Addresses multiple _redirect records and maximum _redirect length

---

docs/README.md

Adds documentation regarding the need to encode URLs in the TXT record since not doing so can cause parsing issues and, as a result, break a user's configuration.
fixes #62

Add documentation regarding encoding URLs

---

path.go

Fix getFinalRecord to find the final non-path record
fixes #59 
```release-note
```

Fix getFinalRecord to find the final non-path record

---

txtdirect.go

Remove rewriting rec.To when it doesn't exist
fixes #81 
```release-note
```

Remove rewriting rec.To when it doesn't exist

---

path.go
txtdirect.go

Adds a wrapper function so that all DNS requests use an absolute zone and also uses the custom or non-custom dialer where applicable.
fixes #85

Add wrapper function for absolute zone and dialer code

---

txtdirect.go
txtdirect_test.go

Implements {uri} placeholder. We can also move these util functions into another package to make the main file cleaner if it makes sense.
fixes #82

Implement {uri} placeholder

---

txtdirect.go
txtdirect_test.go

Fixes a potential bug/misunderstanding with how we handle absolute paths in placeholders. 
Previously the leading `/` would be trimmed, now we keep it. This brings us closer to caddy's behaviour for [placeholders](https://caddyserver.com/docs/placeholders).

Include leading slash in URI and Path placeholders

---

path.go
txtdirect.go

Fixes a bug where port was being used with zone. Also uses query as a global function to remove port from zone and use absolute zone.

Refactor query to globally remove port from zone and use absolute zone

---

txtdirect.go

Adds a new proxy type and uses Caddy's reverse proxy functionality in order to perform proxy requests instead of redirecting.
PoC for #86

Proxy requests instead of redirecting

---

.travis.yml
Makefile
caddy/caddy.go
txtdirect_test.go

Implements a local DNS server for e2e tests. For now, it only contains tests for ``query`` function.
We need to discuss what else we want to test.

Add DNS server mocking for query function

---

txtdirect.go

Proxying currently uses rec.To without checking for placeholders in txt records. This change uses the getBaseTarget function in order to check for placeholders and then parse them before doing proxy requests.
fixes #106

Add support for placeholders in proxy requests

---

.travis.yml
Makefile
caddy/caddy.go
txtdirect.go

Checks for the proxy type in c.Enable and does not run a proxy request if the proxy type is not present. Since proxy requests are currently an experimental feature, they are now disabled by default.
fixes #107

Disable proxy requests by default

---

txtdirect.go

Currently, only www and fallback check the config to see if they should be active before executing. By adding checks for the other record types, they will now be gated if they are not enabled in the config.
fixes #110

Adds feature gates for all types via config

---

txtdirect_test.go

Creates a channel for the DNS server to kill the go routine when the test is finished.
```release-note
```

Fix race condition in e2e tests

---

txtdirect_test.go

Adds e2e tests for Redirect using the mock DNS 
fixes #17 
For now, it only covers ``Redirect`` function, will add functional tests too to cover caddy part. Also is it ok to remove old ``Redirect`` tests?

Add e2e tests using mock DNS server

---

txtdirect_test.go

Add e2e tests for config disable/enable
fixes #109

Add e2e tests for config disable/enable

---

placeholders.go

Adds support for parsing {labelN} placeholders since that feature is not currently supported.
fixes #104

Add parsing for {labelN} placeholder

---

txtdirect.go
txtdirect_test.go

Standardizes DNS records for e2e tests
fixes #121 
```release-note
```

Standardize DNS records for e2e tests

---

placeholders.go
txtdirect.go
txtdirect_test.go

Refactors parsePlaceholders so that it returns errors and triggers fallback when placeholder parsing fails.

Refactor parsePlaceholders when errors occur

---

gometa.go
gometa_test.go
txtdirect.go

Move gometa record defaults to gometa.go
fixes #77

Move gometa record defaults to gometa.go

---

placeholders_test.go
txtdirect_test.go

Adds a number of tests that are needed to ensure that placeholder parsing is working correctly. Also separates placeholder tests from the main TXTDirect tests.
fixes #105 
Additional placeholder tests are needed

[WIP] Placeholder tests

---

docs/README.md
placeholders.go

Adds documentation that explains how multi-level tlds are handled since the current docs do not include that information.
fixes #122

Add documentation regarding how multi-level tlds are handled

---

examples/README.md
placeholders.go

Removes {fragment} placeholder support since it shouldn't be sent to the server and is not something the server supports. Also removes references to fragment in the README.

Remove {fragment} placeholder support

---

dockerv2.go
dockerv2_test.go
txtdirect.go

It defines a new type called ``dockerv2`` that handles docker vanity URLs redirection.
fixes #14 
It's jsut a PoC version and needs more work and discussion.

PoC version of docker vanity urls

---

Makefile

Disable Caddy telemetry by default
fixes #151 
The variable that defines telemetry's status has changed from ``const enableTelemetry`` to ``var EnableTelemetry``
[Source Code](https://github.com/mholt/caddy/blob/764c9ec9560b3aaf39a743679caba2c79bdf9ef6/caddy/caddymain/run.go#L528)
```release-note
```

Disable Caddy telemetry by default

---

placeholders.go
txtdirect.go

This PR adds a query for _redirect._ if the _redirect query isn't found for primary requests. This solves the wildcard issue where we can't set a wildcard _redirect record.
fixes #145

Add a query for _redirect._ if _redirect isn't found

---

txtdirect_test.go

Removes the tests that rely on external DNS
fixes #154 
```release-note
```

Remove usage of external DNS based tests

---

path.go
path_test.go
placeholders.go
placeholders_test.go
txtdirect.go

Adds regex matches as placeholders
fixes #148 
I've passed ``pathSlice`` as a pointer to zoneFromPath because I didn't want to return more than 3 variables. If it's ok to be more than 3, can change it.
```release-note
```

Add regex matches as placeholders

---

dockerv2.go
prometheus.go
txtdirect.go

Removes custom time format from logs and adds host data to logs instead of using `r.URL.String()`
fixes #167 and #168 
```release-note
```

[logging]: Remove custom time format and add host data to logs

---

gometa.go
gometa_test.go
txtdirect.go

Removes .Path from meta tags
fixes #201

[gometa]: Remove .Path from meta tags

---

txtdirect.go

Trigger fallback for requests that are not from docker client.
fixes #207

[dockerv2]: Fix fallback

---

txtdirect.go
txtdirect_test.go

Triggers fallback on requests that are not from `go get`
fixes #205 
```release-note
```

[gometa]: Trigger fallback on requests that are not from go tools

---

txtdirect.go
txtdirect_test.go

Triggers fallback when the request is for 127.0.0.1
fixes #190

Trigger fallback when the request's host is an IP

---

txtdirect.go
txtdirect_test.go

Fixes missing argument in the function call.
P.S: This bug causes master tests to fail.

[fallback]: Fix missing argument in the function call

---

caddy/caddy.go
txtdirect.go
txtdirect_test.go

Replaces "Server" header value with "TXTDirect"
fixes #221

[header]: Replace "Server" header value with "TXTDirect"

---

caddy/caddy.go
caddy/caddy_test.go

Sends logs to ioutil.Discard when log isn't enabled
fixes #220

[logfile]: Send logs to ioutil.Discard when log isn't enabled

---

prometheus.go
txtdirect.go

Adds path metric per host
fixes #174

[prometheus]: Add path metric per host

---

Makefile

Remove manual version pinning from makefile as these are now set within Caddy itself.
```release-note
```

Inherit dependency versions from Caddy

---

record.go
record_test.go
txtdirect.go
txtdirect_test.go

Adds `Referer` header and `ref=` field to record struct
fixes #273

[header]: Add referer header

---

dockerv2.go
dockerv2_test.go
fallback_test.go
gometa.go
gometa_test.go
host.go
path.go
proxy.go
record.go
txtdirect.go

Moves types logic to their own files and uses each type's config struct to pass data.
We didn't have any plans for this change but I thought it may be good to clear the main `Redirect` function a bit and move each type's logic to its own file. We can see this as a step to the plugin-based system idea that we talked about before.
```release-note
```

[redirect]: Move types logic to their own file

---

cmd/txtdirect-validator/main.go
path.go
record.go
record_test.go
setup.go
setup_test.go

Exposes the record parser and adds the validator tool
fixes #263 
The features that might be good to have:
* A flag to pass a URI and use it for parsing the placeholders inside the record
* A flag to pass a config file and use it to parse a complete config (Right now it only lets the user customize enabled types).
`nil`

[validator]: Add the txtdirect-validator tool

---

.travis.yml
dockerv2.go
fallback.go
git.go
gometa.go
host.go
path.go
placeholders.go
prometheus.go
proxy.go
qr.go
setup.go

Fix `go vet` errors and add comments for all the methods and structs
fixes #297

[vet]: Fix `go vet` errors

---

prometheus.go

Fixes startup and register bug
fixes #306 
We didn't need to call `once` twice, the Prometheus `start` function already did run once on the startup.
```release-note
```

[prometheus]: Fix startup and register bug

---

.travis.yml
Makefile
dockerv2.go
e2e/Dockerfile
e2e/dockerv2/main.go
e2e/dockerv2/zonefile
e2e/main.go
txtdirect.go

Adds E2E tests for `dockerv2` type
Not ready yet, we have to add the custom registry as an insecure registry to the docker daemon config.
```release-note
```

[e2e]: Add tests for dockerv2

---

record.go
record_test.go
txtdirect_test.go

Implements the feature to add custom headers using TXT records.
fixes #308 
Nan
*Note: All the header values should be percent-encoded.*
Example for single record:
```
"_redirect.example.com.": "v=txtv0;to=https://example.com;type=host;>TestHeader=TestValue;code=302"
```
Example for chained records using path type:
```
"_redirect.path.example.com.": "v=txtv0;type=path;>TestHeader=TestValue;>TestHeader1=TestValue1"
"_redirect.child.path.example.com.": "v=txtv0;type=host;to=https://example.com;"
```
HSTS Example:
```
"_redirect.example.com.": "v=txtv0;to=https://example.com;type=host;>Strict-Transport-Security=max-age%3D63072000%3B+includeSubDomains%3B+preload+;code=3 …
```

[headers]: Add custom headers using records

---

record.go
record_test.go

Headers now get urldecoded to create valid headers.
Leading and trailing whitespace is trimmed as well.
Fix is already in the v0.4.0 binaries.
```release-note
```

Fix header handling

---

e2e/host/main.go
e2e/host/zonefile
e2e/main.go
e2e/path/main.go
e2e/path/zonefile
path.go
record.go
record_test.go
txtdirect.go

Adds the `use=` field to record to provide a feature like how CNAME records work. The `use=` field can be used to redirect a TXT record request to another upstream zone. Basically use a TXT record that has been specified for another zone address.
~~Still trying to figure out how to fix the bugs on the `path` type, so not ready for a full review.~~
```release-note
```

[record]: Add `use=` field

---

path.go
path_test.go

If the custom regex doesn't need the request query and we add it by default, it will cause some problems and generate a wrong zone address. Fixed this issue by only adding the request query when a custom regex needs it.
```release-note
```

(path): Stop adding query to path by default

---

Makefile

Passes the git commit hash for dev builds via -ldflags.
fixes #328 
```release-note
```

[make]: Show dirty versions in -version flag
