.travis.yml
Still room for (a lot of) improvement
=> Add Docker deployment to CI

gometa.go, gometa_test.go, txtdirect_test.go
I also moved some tests around.
=> Fix gometa root redirection behavior

.travis.yml
=> Add prometheus and realip to Travis build

README.md
Figured it could be good to have this
=> Add Go Report Card to README

caddy/caddy.go, caddy/caddy_test.go, txtdirect.go, txtdirect_test.go
=> Default behavior

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .gitlab/issue_templates/Bug.md, .gitlab/issue_templates/Feature.md, .gitlab/merge_request_templates/Merge Request.md, CHANGELOG.md, CONTRIBUTING.md, docs/README.md, examples/LICENSE, examples/README.md, maintainer-examples/code-copyright-header, maintainer-examples/docs-copyright-header
Base files should be updated for clearer licensing and updated comments.
hf
```release-note
Update base files via reposeed
```
=> Update base files via reposeed

README.md
=> Add logo author

caddy/caddy.go, caddy/caddy_test.go, gometa.go, gometa_test.go, txtdirect.go, txtdirect_test.go
Adds a license header to every code file
Fixes #22
=> Add license header to code files

README.md, docs/README.md, examples/README.md
Adds example on how to use TXTDIRECT
Fixes #20 #21 
This is a work in progress, please don't merge yet. Opening a PR to get feedback on the examples provided
```release-note
Provide examples of TXTdirect usage
```
=> Add examples

.gitignore, Dockerfile, Makefile
Adds a Makefile to allow building locally easily
**Which issue this PR fixes**
Fixes #29 
This is not ready for merge.
```release-note
Add Makefile to project
```
=> Add basic Makefile to build caddy with txtdirect

.travis.yml, Makefile
Makefile was missing a simple clean rule
=> Add clean rule to Makefile

SECURITY.md
=> Add missing security mail

.travis.yml
Previously we only tested if we could build correctly, now we also run tests.
**Which issue this PR fixes**
fixes #45
=> Run tests during CI

path.go, path_test.go, txtdirect.go
Get order from record
fixes #49 and #50 
```release-note
```
=> Simplified regex

txtdirect.go
Parse from= in record
fixes #68 
```release-note
```
=> Parse from= in record

txtdirect.go
Fix redirect loop when root key is not available in record
fixes #70 
```release-note
```
=> Fix redirect loop when root key is not available in record

caddy/caddy.go, path.go, txtdirect.go
Implement Custom DNS Resolver
fixes #4 
```release-note
```
=> Implement Custom DNS Resolver

caddy/caddy.go, txtdirect.go
Order switch cases alphabetically
fixes #78 
```release-note
```
=> Order switch cases alphabetically

.travis.yml, caddy/caddy.go, txtdirect.go
Implements logging for redirects and incoming requests
fixes #37 
We need to talk about what we want to log and what informations we need to include in logs. Now, it only logs the incoming requests and redirects URL.
=> Implement logging

Makefile, txtdirect.go, txtdirect_test.go
Implements more placeholders that are listed in the issue.
fixes #90
=> Add more placeholders

txtdirect.go
Change logs date format
fixes #95 
```release-note
```
=> Change logs date format

path.go, path_test.go, txtdirect.go
Implements custom regex option for parsing path
fixes #51 
The last example in the issue needs more thinking. will find a solution for that later. **(WIP)**
=> Implement custom regex for path

path.go, txtdirect.go, txtdirect_test.go
Simplifies configuration check
fixes #131
=> Simplify configuration check

gometa.go, path.go, placeholders.go, txtdirect.go
Adds comments for most of the functions
fixes #79
=> Add comments for most of the functions

path.go, path_test.go
Adds custom regex with groups support
fixes #98
=> Add custom regex with groups support

dockerv2.go, dockerv2_test.go, txtdirect.go
Adds error handling for dockerv2
fixes #149 
```release-note
```
=> [docerv2]: Add error handling

txtdirect.go
Logs the error when wildcard fallback doesn't exist
fixes #157 
```release-note
```
=> Log the error when wildcard fallback doesn't exist

txtdirect_test.go
Adds path based routing tests for gometa
fixes #116 
Since we already had this feature, I only added tests for it.
```release-note
```
=> Add path based routing tests for gometa

.travis.yml, Makefile, caddy/caddy.go, caddy/caddy_test.go, gometa.go, prometheus.go, txtdirect.go
Adds Prometheus support
fixes #123 
~~``Not ready for reviews yet.``~~
=> Add Prometheus support

gometa.go, gometa_test.go
Adds go-source meta tag support
fixes #142 
```release-note
```
=> Add go-source meta tag support

dockerv2.go, txtdirect.go, txtdirect_test.go
Uses temporary redirect as default redirect code
fixes #187
=> Use temporary redirect as default redirect code

.travis.yml, Dockerfile, Makefile, cloudbuild.yaml
Refactor Makefile and Dockerfile
Remaining:
- Add the project's path dynamically to the Dockerfile (Line 4 and 6)
- Add push target to the makefile
- ...
I will add whatever comes to my mind to the list above, let me know if we need to add something else or change something.
=> Refactor Makefile and Dockerfile

gometa.go, gometa_test.go, gomods.go, txtdirect.go
Fixes gomods storage bugs
fixes #181, #183, #184, #185
partially iterate on #190
=> Fix various bugs

Makefile, cloudbuild.yaml
Fixes Makefile bugs
fixes #194 
```release-note
```
=> Fix Makefile bugs

Makefile
Fixes unknown directive bug
fixes #196
=> (make): Fix unknown directive

gomods.go
Fixes gomods import path parser
fixes #186
=> Fix gomods import path parser

path.go, path_test.go
Fixes index out of range error
fixes #69
=> [path]: Fix index out of range error

Makefile
Add mailout to build so we can reuse build image.
fixes #217
=> Add mailout to build

caddy/caddy.go, dockerv2.go, gometa.go, prometheus.go, txtdirect.go
Adds more metrics and rename current ones
fixes #171, #172, #173, #175
=> [prometheus]: Add more metrics and rename current ones 

txtdirect_test.go
Adds e2e fallback tests
fixes #206
=> [test]: Add e2e fallback tests

caddy/caddy.go, caddy/caddy_test.go, txtdirect.go
Fixes empty value panic and add tests
fixes #215
=> [logfile]: Fix empty value panic and add tests

Makefile, caddy/caddy.go
Adds caddy-prometheus middleware as the first middleware
fixes #169
=> [make]: Add caddy-prometheus middleware as the first middleware

dockerv2.go, prometheus.go, txtdirect.go, txtdirect_test.go
Adds fallback type to fallback counter
fixes #172
=> [prometheus]: Add fallback type to fallback counter

Makefile, caddy/caddy.go, caddy/caddy_test.go, tor.go, txtdirect.go
fixes #143
```release-note
Clearnet -> Tor proxy type added
```
=> [Tor] Add first PoC for new tor type

tor.go
Add placeholder support to tor type.
fixes #235
```release-note
```
=> [tor] Support placeholders

Makefile
=> Move to Go 1.12

.travis.yml
=> Simplify Travis

Makefile
Fixes append on every make run
fixes #244
=> [make]: Append only once to go.mod

proxy.go, txtdirect.go
Replaces the asset URIs inside the response body
fixes #232
=> [proxy]: Replace asset URIs inside the response body

txtdirect.go, txtdirect_test.go
Adds more tests and "www" support
fixes #230
=> [fallback] Add more tests and "www" support

gometa.go, gometa_test.go, txtdirect.go
Revert #211 changes
```release-note
```
=> (gometa): Revert #211 changes

cmd/txtdirect/main.go, go.mod, go.sum, gomods.go, prometheus.go, proxy.go, setup.go, setup_test.go, tor.go, txtdirect_test.go
Changes Caddy's import path
fixes #270
=> [caddy]: Change Caddy's import path

fallback.go, fallback_test.go, git.go, git_test.go, path.go, record.go, txtdirect.go, txtdirect_test.go
Adds `git` type and fallback tests for it
fixes #278
=> [git]: Add type and fallback tests for it

fallback.go, path.go, txtdirect.go, txtdirect_test.go
Adds predefined regex mode
fixes #256 
=> [path]: Add predefined regex mode

path.go
Normalizes the path after adding it to the context
```release-note
```
=> [path]: Normalize the path after adding it to the context

.github/workflows/go.yml
Use godocit to auto create documentation issues, when a docs needed label is added.
=> Add godocit action

e2e/path/main.go, e2e/path/zonefile, path.go, record.go
Fixes predefined regex order bug
related #319 
```release-note
```
=> [path]: Fix predefined regex order bug

e2e/dockerv2/zonefile, e2e/gometa/zonefile, e2e/host/main.go, e2e/host/txtdirect.config, e2e/host/zonefile, e2e/path/main.go, e2e/path/zonefile, path.go
Fixes chaining's request loop bug and add more E2E tests
```release-note
```
=> [path]: Fix chaining's request loop bug and add more E2E tests

prometheus.go, setup_test.go, txtdirect.go
Adds whitelist for path metrics
fixes #264 
```release-note
```
=> [metrics]: Add whitelist for path metrics

record.go
Fixes dockerv2 records to= field check
```release-note
```
=> [record]: Fix dockerv2 records to= field check

e2e/dockerv2/main.go, e2e/dockerv2/zonefile, e2e/main.go
Adds pull tests for `dockerv2`
fixes #341 
*Needs rebase before the merge. Depends on #343*
```release-note
```
=> [e2e]: Add pull tests for dockerv2
